services:
  hugo:
    container_name: cht-hugo
    image: cht-hugo:0.152.2 # Should match the hugo version in .tool-versions
    build:
      context: .
    ports:
      - 1313:1313
    volumes:
      - ./:/src
