baseURL = "https://docs.communityhealthtoolkit.org/"
title = "Community Health Toolkit"

refLinksErrorLevel = "ERROR"
disableKinds = ["taxonomy"]

# Will give values to .Lastmod etc.
enableGitInfo = true

enableEmoji = true
hasCJKLanguage = true
enableRobotsTXT = false
enableInlineShortcodes = true

# Language settings
contentDir = "content/en"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
# Useful when translating.
enableMissingTranslationPlaceholders = true

[module]
  proxy = "direct"
  # uncomment line below for temporary local development of module
  # replacements = "github.com/imfing/hextra -> ../../hextra"
  [module.hugoVersion]
    extended = true
  [[module.imports]]
    path = "github.com/imfing/hextra"
    disable = false

[privacy.youtube]
privacyEnhanced = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
      noClasses = false

[[menu.main]]
name = "Search"
weight = 4

  [menu.main.params]
  type = "search"

[[menu.main]]
name = "GitHub"
weight = 5
url = "https://github.com/medic"

  [menu.main.params]
  icon = "github"

[[menu.sidebar]]
identifier = "more"
name = "More"
weight = 1

  [menu.sidebar.params]
  type = "separator"

[[menu.sidebar]]
identifier = "forum"
name = "CHT Forum"
url = "https://forum.communityhealthtoolkit.org/"
weight = 2

[[menu.sidebar]]
identifier = "docs"
name = "Create documentation issue ↗"
url = "https://github.com/medic/cht-docs/issues/new"
weight = 3

[[menu.sidebar]]
identifier = "privacyPolicy"
name = "Privacy Policy ↗"
url = "https://docs.google.com/document/d/1MaI1rgYMNyCZF2eEjBuvnBDoCYHDKlx4k_N5pkDiWu8/edit?usp=sharing"
weight = 4

## Configuration for BlackFriday markdown parser: https://github.com/russross/blackfriday
[blackfriday]
plainIDAnchors = true
hrefTargetBlank = true
angledQuotes = false
latexDashes = true

# Image processing configuration.
[imaging]
resampleFilter = "CatmullRom"
quality = 75
anchor = "smart"

[services]
[services.googleAnalytics]
# Comment out the next line to disable GA tracking. Also disables the feature described in [params.ui.feedback].
id = "G-98W4V2NTPJ"

# Language configuration

[languages]
[languages.en.params]
title = "Community Health Toolkit"
description = "Digital health initiatives in the hardest-to-reach areas"
languageName ="English"
# Weight used for sorting.
weight = 1
# [languages.fr]
# title = "Community Health Toolkit"
# description = "Technologie open source pour un nouveau modèle de santé qui touche tout le monde."
# languageName ="Français"
# contentDir = "content/fr"
time_format_default = "02.01.2006"
time_format_blog = "02.01.2006"

# Everything below this are Site Params

[params]
displayUpdatedDate = true
copyright = "CHT"
privacy_policy = "https://docs.google.com/document/d/1MaI1rgYMNyCZF2eEjBuvnBDoCYHDKlx4k_N5pkDiWu8/edit?usp=sharing"
nodeVersion = "22"
npmVersion = "10"

# Custom shortcodes and partial will error on broken references unless set to "WARNING"  
linkErrorLevel = "ERROR"

# First one is picked as the Twitter card image if not set on page.
# images = ["images/project-illustration.png"]

github_repo = "https://github.com/medic/cht-docs"

# Google Custom Search Engine ID. Remove or comment out to disable search.
gcs_engine_id = "004290134484316368579:gvcrxmetz4s"

# Enable Algolia DocSearch
algolia = false

# Enable Lunr.js offline search
offlineSearch = false

# User interface configuration
[params.ui]
# Enable to show the side bar menu in its compact state.
sidebar_menu_compact = true
# Enable folding sections of the sidebar
sidebar_menu_foldable = true
#  Set to true to disable breadcrumb navigation.
breadcrumb_disable = false
#  Set to true to hide the sidebar search box (the top nav search box will still be displayed if search is enabled)
sidebar_search_disable = false
#  Set to false if you don't want to display a logo (/assets/icons/logo.svg) in the top nav bar
navbar_logo = true
# Set to true to enable the About link in the site footer
footer_about_enable = false
# Set to true to enable the display of a light/dark mode menu in the navbar
showLightDarkModeMenu = true

[Home]
RelPermalink= "communityhealthtoolkit.org"

[related]
  includeNewer = true
  toLower = false
 [[related.indices]]
    name = "keywords"
    weight = 1

[security.exec]
# To work with asdf, ref https://github.com/gohugoio/hugo/issues/9811
osEnv = ['(?i)^((HTTPS?|NO)_PROXY|PATH(EXT)?|APPDATA|TE?MP|TERM|HOME|ASDF_DIR)$']

  [params.navbar]
  displayTitle = false
  displayLogo = true
  width = "wide"

    [params.navbar.logo]
    path = "icons/logo.svg"
    dark = "icons/logo-dark.svg"
    width = 300

  [params.page]
  width = "normal"

  [params.theme]
  default = "system"
  displayToggle = true

  [params.footer]
  enable = true
  displayCopyright = true
  displayPoweredBy = false
  width = "normal"

  [params.search]
  enable = true
  type = "flexsearch"

    [params.search.flexsearch]
    index = "content"
    tokenize = "forward"

  [params.editURL]
  enable = true
  base = "https://github.com/medic/cht-docs/edit/main/content"

[params.highlight.copy]
enable = true
display = "hover"

  [params.comments]
  enable = false
  type = "giscus"
